[build]
  command = "npm install"
  publish = "public"

[dev]
  command = "npm run local"
  port = 3000
  publish = "public"

# Simple SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
